name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm Dependencies
      run: npm install
    - name: Execute Unit Tests
      run: npm run test:unit
    - name: Display My SoftUni Username
      run: echo 'PavlinGalabov'

  run_ui_tests:
    needs: build_and_unit_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm Dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install   
    - name: Start the App
      run: npm run start &
    - name: Execute the UI Tests
      run: npm run test:ui

  deploy:
    needs: run_ui_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true 
